[package]
name = "swap_or_not_shuffle"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2021"

[[bench]]
name = "benches"
harness = false

[dev-dependencies]
criterion = "0.3.3"

[dependencies]
eth2_hashing = { path = "../../crypto/eth2_hashing" }
ethereum-types = "0.14.1"

[features]
arbitrary = ["ethereum-types/arbitrary"]
